Feature/tweet
shinonome-inc/backend-final-assignment-yota pull request #3
Opened 2023-08-22 10:27 UTC by yota33166

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-08-23 10:03 UTC, masaya09 requested changes

2023-08-23 10:03 UTC, masaya09 commented on accounts/tests.py
> +from tweets.models import Tweet
![must-badge](https://img.shields.io/badge/review-must-red.svg)
以前のレビュー漏れですね。
5行目のsettingsは django.conf からimportするようにしてください。

2023-08-23 10:03 UTC, masaya09 commented on accounts/tests.py
> +            Tweet.objects.create(author=self.user, text=f"Test {i+1}")
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
 10個作成した理由はなんですか？

ここで確認したいことはなんでしょうか。実施しているテストを見る限り、ツイートが表示されていることがわかれば良さそうです。その場合、1つでも同様の確認ができそうです。無駄なテストデータの作成はテスト実行を遅らせることになります。

テストで確認したいことと必要なテストデータに関して改めて考えてみてください

2023-08-23 10:03 UTC, masaya09 commented on accounts/views.py
> +        context["tweets"] = Tweet.objects.select_related("author").filter(author=user)
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
ここはまだクラスビューに慣れてないと思うので、細かい指摘になります。

DetailViewをここで用いてますが、その選定理由はなんでしょうか？と聞いた場合に答えられるようになるために以下の考え方を持ってください。

おそらくslugifieldを容易に使いたいためにDetailViewを用いたのだと考えられますが、
今回、プロフィール画面に表示されるデータはtweetデータが1番多くなりそうです。そうすると、例えば2000個くらいツイートしている場合に現状だと2000個のツイートデータをプロフィール画面を訪れるたびに表示することになります。これは表示するまでに時間かかる処理になります。

それを防ぐために使われるのがページネーションなのですが、この設定はListViewを用いると簡単に用いることができます。

DetailViewを用いた中でツイートモデルにページネーションを適用するよりも、ListViewを用いてListViewの中でURLのslugの値からuserを絞り込む方がこの場合楽です。

ListViewの場合、get_context_data内でUser.objects.get(username=kwargs...)のような書き方すれば簡単にURLの値からユーザーの単一モデルは取ってこれます。（get_object_or_404用いた方が適切）

2023-08-23 10:03 UTC, masaya09 commented on mysite/urls.py
> +from django.conf import settings
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
こっちではできてますね

2023-08-23 10:03 UTC, masaya09 commented on tweets/forms.py
> +            raise forms.ValidationError("テキストは280文字以下で入力してください。")
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
cleaned_dataはバリデーションが通った後に取得されるデータが格納されるところなので、ここからさらにバリデーションをかけるのは違和感あります。このような記述にした理由はなんでしょうか？参考にしたサイトもあれば、それのURLお願いします

2023-08-23 10:03 UTC, masaya09 commented on tweets/models.py
> +    published_date = models.DateTimeField(blank=True, null=True)
![must-badge](https://img.shields.io/badge/review-must-red.svg)
DateTimeFieldを用いる場合、命名は `~_at` にした方が良いです。
created_atは更新不可にしたいです。`editable=False` をつけましょう。

published_atって必要ですか？どういうものを意図してつけたのでしょうか？
下書き用の状態を作るためですか？

モデルのフィールドに関しては慎重に考えてください。自分が作るツイート機能に必要なカラムなのか？という視点を持ちましょう。

2023-08-23 10:03 UTC, masaya09 commented on tweets/models.py
> +    text = models.TextField()
**![must-badge](https://img.shields.io/badge/review-must-red.svg)**
ツイートのバリデーションが280字以内となってますが、その程度かつ文字数制限つけるなら基本的にCharFieldで良いです。TextFieldは文字数制限を別につけなくていいものだとか、数千 ~ 数万文字を書くような場合とかに用いるようなフィールドです。

特に今回は文字数でバリデーションをかけたいみたいなので尚更CharFieldを用いた方が良さそうです。

2023-08-23 10:03 UTC, masaya09 commented on tweets/tests.py
> +            Tweet.objects.create(author=self.user, text=f"Test {i+1}")
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
こちらも10個もテストデータは必要ですか？

2023-08-23 10:03 UTC, masaya09 commented on tweets/views.py
> +        return context
![must-badge](https://img.shields.io/badge/review-must-red.svg)
model = Tweet としてるので、get_context_data内に記述するのは不要です。
select_relatedを用いたい場合、querysetアトリビュートに記述しましょう。

以下でListView内の処理の流れをのぞいてみてください。
https://ccbv.co.uk/projects/Django/4.2/django.views.generic.list/ListView/

2023-08-23 10:03 UTC, masaya09 commented on tweets/views.py
> +        return response
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
```suggestion
        return super().form_valid(form)
```
これでも良さそうですね

2023-08-23 10:03 UTC, masaya09 commented on tweets/views.py
> +    queryset = Tweet.objects.select_related("author")
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
こっちではできてますね。ListViewもこのようにしましょう

2023-08-23 10:03 UTC, masaya09 commented on tweets/views.py
> +        return self.object.author == self.request.user
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
よく資料読み込まれていていいですね。この記述できる人はなかなかいませんよ

2023-08-23 23:16 UTC, yuki00900 approved these changes

2023-08-24 08:12 UTC, yota33166 commented on tweets/forms.py
> +            raise forms.ValidationError("テキストは280文字以下で入力してください。")
PlayGroundのテキストにおいて、SignupViewでformからcleaned_dataを取得していたため、それを参考にしました。が、cleaned_dataを取得しているのはform_valid実行後でした。
上記の私のコード内では、self.dataでtextを取得した方が良さそうです。ご指摘ありがとうございます!

2023-08-24 08:32 UTC, yota33166 commented on accounts/tests.py
> +            Tweet.objects.create(author=self.user, text=f"Test {i+1}")
「全て」のツイートが「漏れなく」表示されているかの確認のため、テストデータを複数用意したのですが、不要ですか?
正直、テストデータの内容や量に関しては、何が適切かよく分かっていない状況です。

2023-08-24 09:22 UTC, masaya09 commented on accounts/tests.py
> +            Tweet.objects.create(author=self.user, text=f"Test {i+1}")
テストは必要最低限で確かめるべきことが確かめられればOKです

2023-08-26 02:23 UTC, masaya09 requested changes

2023-08-26 02:23 UTC, masaya09 commented on tweets/views.py
> +        return super().form_valid(form)
![must-badge](https://img.shields.io/badge/review-must-red.svg)
form.saveは、CreateViewが継承しているModelFormMixinのform_validで実施してるので不要です。
super().form_valid(form)を呼び出してるため、ここできちんとform.saveされています。

実際のコード
https://ccbv.co.uk/projects/Django/4.2/django.views.generic.edit/CreateView/#form_valid

2023-08-26 02:23 UTC, masaya09 commented on tweets/views.py
> +        tweet.created_at = timezone.now()
![must-badge](https://img.shields.io/badge/review-must-red.svg)
created_atはdefaultでtimezone.now入れてたのでこの記述は不要です

2023-08-26 02:23 UTC, masaya09 commented on tweets/tests.py
> +        self.url = reverse("tweets:delete", kwargs={"pk": 1})
![must-badge](https://img.shields.io/badge/review-must-red.svg)
kwargsの指定は直接記述せずに、以下のようにして対応しましょう

102行目で作成したツイートを変数に入れる
```python
self.tweet = Tweet.objects.create(author=self.user, text="Test")
```
```python
url = reverse("tweets:delete", kwargs={"pk": self.tweet.id})
```

2023-08-26 02:23 UTC, masaya09 commented on tweets/tests.py
> +        self.url = reverse("tweets:delete", kwargs={"pk": 1})
![must-badge](https://img.shields.io/badge/review-must-red.svg)
また、setUpメソッド以外の関数内で変数を定義するときは self. をつけないでください。これをつけるとインスタンス変数となり、他のメソッド内でも呼び出し可能になってスコープが乱れます。不用意な変数のスコープ拡大には気をつけてください。

2023-08-26 02:23 UTC, masaya09 commented on tweets/tests.py
> +        self.url = reverse("tweets:detail", kwargs={"pk": 1})
![must-badge](https://img.shields.io/badge/review-must-red.svg)
ここもpkは直接記述しないようにすること

2023-08-26 02:23 UTC, masaya09 commented on tweets/tests.py
> +            Tweet.objects.create(author=self.user, text=f"Test {i+1}")
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
DetailViewの検証にツイートは10個も必要ないように思えますが、どういった意図がありますか？

2023-08-26 02:23 UTC, masaya09 commented on accounts/views.py
> +        return context
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
ここは慣れないと難しいですが、model = Tweet とすると、get_querysetメソッドによってTweetモデルが実行されることになり、結果として、context_object_name = "profile" のところでゲットできる値は、存在するツイートデータのうち10個のツイートとなってしまいます。

実装ヒント
41行目の処理を、get_querysetメソッドをオーバーライドして実施してみてください。
context_object_nameは model = Tweet としてる時点で tweets となるので、context_object_nameを新たに定義する必要はないです。

2023-08-26 02:23 UTC, masaya09 commented on accounts/views.py
> +        context["username"] = user
![must-badge](https://img.shields.io/badge/review-must-red.svg)
context名は Userモデルが入ってるので target_user などにした方が良さそうです

2023-08-26 03:29 UTC, yota33166 commented on tweets/tests.py
> +            Tweet.objects.create(author=self.user, text=f"Test {i+1}")
修正漏れですね...
特に意図はないので直しておきます！

2023-08-28 04:32 UTC, masaya09 commented on accounts/views.py
> +        context["target_user"] = user
![must-badge](https://img.shields.io/badge/review-must-red.svg)
`get_object_or_404(User, username=username)`にてUserモデルを2回呼んでしまってるので、ここは1回にまとめたいです（SQLが発行されて処理速度の低下につながるので）。先に実行されるメソッド内でインスタンス変数として定義すれば、その後に実行されるメソッド内でアクセスすることができます。

このテクニックはすでにTweetDeleteViewにて実装されてます。
実行順はListViewの実装コードを覗いてみて、どこで get_queryset, get_context_dataが呼ばれてるか確認してみてください。
https://ccbv.co.uk/projects/Django/4.2/django.views.generic.list/ListView/

2023-08-28 04:32 UTC, masaya09 commented on templates/tweets/home.html
> +{% for tweet in object_list %}
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
HomeViewはListViewを継承しており、model = Tweet と書いてるので context_object_name として tweets 
 でアクセスすることが可能になってます。

そのため、object_list ではなく、ここは tweets としたほうが良いですね

2023-08-28 04:32 UTC, masaya09 commented on tweets/views.py
> +        tweet.author = self.request.user
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
次のようにすれば1行で書くことも可能です
```suggestion
        form.instance.author = self.request.user
```

2023-08-28 04:32 UTC, masaya09 commented on tweets/views.py
> +class TweetDeleteView(UserPassesTestMixin, DeleteView):
![must-badge](https://img.shields.io/badge/review-must-red.svg)
TweetDeleteViewにて、LoginRequiredMixinを継承し忘れてますね

2023-08-30 03:17 UTC, yota33166 commented on templates/tweets/home.html
> +{% for tweet in object_list %}
tweetsにすると何も表示されなくなるのですが、tweet_listでは正しく表示されます。tweet_listでも良いでしょうか？

2023-08-30 13:07 UTC, masaya09 commented on templates/tweets/home.html
> +{% for tweet in object_list %}
すみません、デフォルトは model名_list でしたね。
context_object_name = "tweets" とすればtweetsでアクセスできますが、修正するかは任せます！

2023-08-30 13:26 UTC, masaya09 requested changes

2023-08-30 13:26 UTC, masaya09 commented on templates/base.html
> +            </ul>
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
sign upボタンはログイン中は表示したくないですね

2023-08-30 13:26 UTC, masaya09 commented on templates/tweets/detail.html
> +    {% endif %}
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
削除ボタンがツイート文の上にあるのは違和感あります

2023-08-30 13:26 UTC, masaya09 commented on templates/tweets/detail.html
> +</div>
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
戻るボタンがあると便利ですね。一応一番上に表示してるホームボタンがありますが、戻るボタンあったほうが親切です

2023-08-30 13:26 UTC, masaya09 commented on templates/tweets/detail.html
> +    <p>published: {{ tweet.created_at }}</p>
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
publishedではなく作成日とした方がいいでしょう。また、作成日もツイート文よりも下にあった方がいいイメージあります。

2023-08-30 13:26 UTC, masaya09 commented on templates/tweets/home.html
> +</div>
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
詳細画面と一覧表示のツイート表示が同じ内容なので、ここを別ファイルに抜き出して include して用いると良さそうです

2023-08-30 13:26 UTC, masaya09 commented on tweets/models.py
> +        self.save()
![must-badge](https://img.shields.io/badge/review-must-red.svg)
publishメソッド不要です

2023-08-30 13:26 UTC, masaya09 commented on tweets/tests.py
> +        self.assertIn("このフィールドは必須です。", form.errors["text"])
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
これはちょっとした書き方のコツですが、テストを見やすくする方法として次のように、準備、実行、検証のところで改行すると良いです。
```suggestion
    def test_failure_post_with_empty_content(self):
        # 準備
        invalid_data = {
            "author": self.user,
            "text": "",
        }
        # 実行
        response = self.client.post(self.url, invalid_data)
        form = response.context["form"]
        # 検証
        self.assertEqual(response.status_code, 200)
        tweet_in_db = Tweet.objects.filter(author=invalid_data["author"], text=invalid_data["text"])
        self.assertFalse(tweet_in_db.exists())
        self.assertFalse(form.is_valid())
        self.assertIn("このフィールドは必須です。", form.errors["text"])
```

2023-08-31 10:24 UTC, masaya09 requested changes
![must-badge](https://img.shields.io/badge/review-must-red.svg)
htmlファイルのインデントが2だったり4だったりします。どちらかに統一してください。

2023-08-31 10:24 UTC, masaya09 commented on templates/welcome/welcome.html
> +{% endblock %}
![must-badge](https://img.shields.io/badge/review-must-red.svg)
EOF起きてます

2023-08-31 10:24 UTC, masaya09 commented on templates/show_tweet.html
![must-badge](https://img.shields.io/badge/review-must-red.svg)
このファイルはtweetに関係してるので、tweetフォルダ内におきたいです

2023-08-31 10:24 UTC, masaya09 commented on templates/show_tweet.html
> +                </svg>
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
svgのこのコードを、例えば以下のようなフォルダとファイルを用意して、ファイル内に記述すると画像を分離できます。変更するかは任せます。なぜassetsというフォルダを用いてるのかは調べてみてください。
```svg
assets/images/delete_button.svg

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="icon" x="0px" y="0px" viewBox="0 0 1000 1000" style="enable-background:new 0 0 1000 1000;" width="18" xml:space="preserve"> <path d="M840,180c0-22.1-17.9-40-40-40H620v-40c0-22.1-17.9-40-40-40H420c-22.1,0-40,17.9-40,40v40H200c-22.1,0-40,17.9-40,40v100 h41.1l40.1,660h517.6l40.1-660H840V180z M420,97h160v43H420V97z M200,178h600v64H200V178z M721.2,900H278.8l-37.6-620h517.5 L721.2,900z M520,820h-40V380h40V820z M359.1,820l-18.3-440h40l18.3,440H359.1z M640.9,820h-40l18.3-440h40L640.9,820z"/>
  <path xmlns="http://www.w3.org/2000/svg" d="M840,180c0-22.1-17.9-40-40-40H620v-40c0-22.1-17.9-40-40-40H420c-22.1,0-40,17.9-40,40v40H200c-22.1,0-40,17.9-40,40v100 h41.1l40.1,660h517.6l40.1-660H840V180z M420,97h160v43H420V97z M200,178h600v64H200V178z M721.2,900H278.8l-37.6-620h517.5 L721.2,900z M520,820h-40V380h40V820z M359.1,820l-18.3-440h40l18.3,440H359.1z M640.9,820h-40l18.3-440h40L640.9,820z"/>
</svg>
```

2023-08-31 10:26 UTC, masaya09 requested changes

2023-08-31 10:26 UTC, masaya09 commented on templates/welcome/welcome.html
> +</nav>
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
ここも、ログイン時はログアウトボタンを表示したいです。ログアウト時は逆に現在表示してるものを表示したいです

2023-08-31 10:49 UTC, yota33166 commented on templates/show_tweet.html
> +                </svg>
Twitter(現X) ではHTMLにsvgを直書きしてたので、このままにしておきます!
assetsフォルダについては、後々使えそうなので調べておきます!

2023-08-31 11:14 UTC, yota33166 commented on templates/welcome/welcome.html
> +</nav>
welcome.htmlはログアウト時にしか呼び出されないので、機能的には問題ないと思います。

2023-08-31 12:09 UTC, masaya09 commented on templates/welcome/welcome.html
> +</nav>
ログインしててもURL直接叩けば呼べますね。ログアウト時にしか呼び出されないということはないです

2023-08-31 12:22 UTC, yota33166 commented on templates/welcome/welcome.html
> +</nav>
意図を理解しました！修正します！

2023-08-31 12:27 UTC, masaya09 commented on templates/welcome/welcome.html
> +    {% endif %}
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
ログインできてれば Sign up を表示する必要はなさそうです

2023-08-31 12:33 UTC, masaya09 approved these changes
![Deadpool LGTM](https://media.giphy.com/media/XD9AhPUPVsGu0hG3YD/giphy.gif)

2023-08-31 12:33 UTC, merged