Feature/follow
shinonome-inc/backend-final-assignment-yota pull request #4
Opened 2023-09-03 16:09 UTC by yota33166

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-09-06 16:50 UTC, nta808015 requested changes
全体的によく書けていると思いました。
いくつかコメントを残しておいたので確認と修正の方よろしくお願いします。

2023-09-06 16:50 UTC, nta808015 commented on accounts/admin.py
> +from .models import FollowRelation, User
ここでは、FollowRelationではなくFriendShipをインポートした方が良いと思ったのですが、FollowRelationをインポートした理由があれば教えてほしいです。

2023-09-06 16:50 UTC, nta808015 commented on accounts/views.py
> +        try:
tryでくくるのは例外が発生する可能性のある1行だけなので、複数行にわたって処理を記述しないようにしましょう。(どこでエラーが起きているのかがわかりにくく混乱するため。)

2023-09-07 02:57 UTC, yota33166 commented on accounts/admin.py
> +from .models import FollowRelation, User
私のmodelでは実装していないのですが、FriendShipとはどのようなものでしょうか？調べても分かりませんでした。
フォローフォロワーの関係を記録する中間テーブルとしてFollowRelationモデルを使用しているので、そのままimportしています。

2023-09-07 03:18 UTC, yota33166 commented on accounts/views.py
> +        try:
![スクリーンショット (160)](https://github.com/shinonome-inc/backend-final-assignment-yota/assets/105335694/8588f49e-e89d-4ac4-a4c9-a20ec00b0931)
![スクリーンショット (161)](https://github.com/shinonome-inc/backend-final-assignment-yota/assets/105335694/a3f47d42-a359-4188-ae43-bb4be689267e)

clean_same_personメソッドと、clean_duplicationメソッドは別々のエラーメッセージを表示するようにしています。

ここではtry文は使わない方が良いですか？それとも、try文の書き方を変えたほうが良いのですか？

2023-09-07 05:55 UTC, nta808015 commented on accounts/admin.py
> +from .models import FollowRelation, User
OKです。命名が的外れでなく、機能も正しく動作しているなら修正は不要です。

2023-09-07 05:55 UTC, nta808015 commented on accounts/views.py
> +        try:
try文を使用している点についてはとてもいいと思います！
しかし、try文は1行しかくくらないとわかりにくくなるため書き方だけ修正した方が良いと思います。

2023-09-07 07:39 UTC, nta808015 commented
1次レビューLGTMです！

2023-09-09 02:47 UTC, Yamakou621 commented
よく書けていると思います！modelの書き方もよいです！良いね機能も頑張ってください！
レビューが遅くなりすみません(._.)

2023-09-09 02:48 UTC, merged