フォロー機能：DB制約の追加
shinonome-inc/backend-final-assignment-yota pull request #5
Opened 2023-09-11 02:04 UTC by yota33166

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-09-11 05:29 UTC, masaya09 requested changes

2023-09-11 05:29 UTC, masaya09 commented on accounts/models.py
> +        ]
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
Django4.1から、UniqueConstraint, CheckConstraintにviolation_error_messageを付与する事ができます。こちらを用いれば、31行目位以降に記述しているバリデーション処理は不要になります。

https://docs.djangoproject.com/en/4.2/ref/models/constraints/#checkconstraint

2023-09-11 06:13 UTC, masaya09 reviewed
1つ目のコメントをミスで閉じてしまったので再度

2023-09-11 06:13 UTC, masaya09 commented on accounts/models.py
> +        ]
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
Django4.1から、UniqueConstraint, CheckConstraintにviolation_error_messageを付与する事ができます。こちらを用いれば、31行目位以降に記述しているバリデーション処理は不要になります。

https://docs.djangoproject.com/en/4.2/ref/models/constraints/#checkconstraint

2023-09-13 09:32 UTC, masaya09 requested changes
followの時はバリデーションエラー出ますが、unfollow時は出ないのでfollowと同様にunfollowにもバリデーション実装お願いします

2023-09-13 09:32 UTC, masaya09 commented on accounts/views.py
> +            follow_relation.full_clean()
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
現在UniqueContraintでエラーを起こすと以下のようになります
<img width="1049" alt="スクリーンショット 2023-09-13 18 23 26" src="https://github.com/shinonome-inc/backend-final-assignment-yota/assets/74097011/aeaf5e4a-c00e-47f8-8042-0195c8a46370">

エラーレスポンスとして400が返るのはいいのですが、エラーメッセージがデフォルトになってるみたいです
<img width="871" alt="スクリーンショット 2023-09-13 18 23 49" src="https://github.com/shinonome-inc/backend-final-assignment-yota/assets/74097011/dd9429d8-4943-4ed0-8287-57ec83f8d900">

2023-09-13 09:32 UTC, masaya09 commented on accounts/views.py
> +            follow_relation.full_clean()
CheckConstraintの方はきちんとできてそうですね。ただ、どちらにせよエラーメッセージが剥き出しの状態なので、自分自身をフォローすることはできない、とだけ表示したいですね。

<img width="527" alt="スクリーンショット 2023-09-13 18 28 57" src="https://github.com/shinonome-inc/backend-final-assignment-yota/assets/74097011/29e4e997-30eb-44a4-82f7-a176513a43e4">
<img width="875" alt="スクリーンショット 2023-09-13 18 30 12" src="https://github.com/shinonome-inc/backend-final-assignment-yota/assets/74097011/e0db7d0a-6179-48d3-985e-5e4edd5ea7f9">

2023-09-17 13:41 UTC, yota33166 commented on accounts/views.py
> +            follow_relation.full_clean()
Unfollow時にもエラーメッセージが出るようになったのですが、例外処理として実装したほうが良いのでしょうか？

2023-09-19 09:14 UTC, masaya09 commented on accounts/views.py
> +            return HttpResponseBadRequest("存在しないフォローです")
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
この処理でも今回は問題ないと思いますが、follow_relationはクエリセットなので、existsで明確に存在値評価をした方がここでは良さそうだと思いました。（エラー文の内容からも存在値チェックが良さそうです）

2023-09-24 11:48 UTC, masaya09 approved these changes
![Leo Clap](https://media4.giphy.com/media/gLu90OMjz4j3hAkJk2/giphy.gif?cid=47028fa87k40eht04wowr73fdbt38jla6svo7yzd9kembf70&ep=v1_gifs&rid=giphy.gif&ct=g)

2023-09-24 11:48 UTC, merged